parameters:
    product_images_dir: '%kernel.project_dir%/public/uploads/products'
    app.mail_from: '%env(APP_MAIL_FROM)%'
    ml_api_base_url: '%env(resolve:ML_API_BASE_URL)%'

    gemini_default_model: 'gemini-2.0-flash'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    gemini_model: '%env(default:gemini_default_model:GEMINI_MODEL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MlApiClient:
        arguments:
            $baseUrl: '%ml_api_base_url%'

    App\Service\GeminiClient:
        arguments:
            $apiKey: '%gemini_api_key%'
            $model: '%gemini_model%'

    App\Service\OrderMailer:
        arguments:
            $fromEmail: '%app.mail_from%'

    App\Service\InvoicePdfGenerator: ~